// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9b7ZHH4BP0dAhAkxn-cmKQN1eWM35PmE',
    appId: '1:720089612420:web:adefa5501cecd264ec02d1',
    messagingSenderId: '720089612420',
    projectId: 'a-few-words',
    authDomain: 'a-few-words.firebaseapp.com',
    storageBucket: 'a-few-words.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1rOmBOgfr1oO4zRrpupc6kARfmI9gI8c',
    appId: '1:720089612420:android:f99ccbfe7023e2bbec02d1',
    messagingSenderId: '720089612420',
    projectId: 'a-few-words',
    storageBucket: 'a-few-words.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLPkYsbfWSsVVVgekStWETqCLnZGZwZPM',
    appId: '1:720089612420:ios:8878286b2450c09bec02d1',
    messagingSenderId: '720089612420',
    projectId: 'a-few-words',
    storageBucket: 'a-few-words.appspot.com',
    iosClientId: '720089612420-tbpqir9hpukt3lobmeactvcufibmnogh.apps.googleusercontent.com',
    iosBundleId: 'com.aliakseibrown.afewwords.aFewWords',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLPkYsbfWSsVVVgekStWETqCLnZGZwZPM',
    appId: '1:720089612420:ios:8878286b2450c09bec02d1',
    messagingSenderId: '720089612420',
    projectId: 'a-few-words',
    storageBucket: 'a-few-words.appspot.com',
    iosClientId: '720089612420-tbpqir9hpukt3lobmeactvcufibmnogh.apps.googleusercontent.com',
    iosBundleId: 'com.aliakseibrown.afewwords.aFewWords',
  );
}
